version: '2'
services:
  web:
    container_name: web-bolton
    image: nginx:1.13
    links:
      - php
    environment:
      WEB_HOSTNAME: bolton.local
    ports:
      - "8080:80"
      - "8040:8040"
    volumes:
      - "./etc/nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf"
      - "./etc/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf"
    volumes_from:
      - php
  php:
    container_name: php-bolton
    build: ./php
    image: docker_bolton/php
    links:
      - db
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ../src:/var/www/bolton
  db:
    container_name: db-bolton
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bolton
      POSTGRES_PASSWORD: q1w2e3
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
